# Generated by Django 4.0.2 on 2022-02-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('app', '0002_telegramuser'), ('app', '0003_telegramuser_id_alter_telegramuser_username'), ('app', '0004_remove_telegramuser_about_telegramuser_bio_and_more')]

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('profile_photo', models.ImageField(blank=True, upload_to='')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bio', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
